# Generated by Django 3.2.9 on 2021-11-15 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('receiptID', models.AutoField(primary_key=True, serialize=False)),
                ('enquiryDate', models.DateField(auto_now_add=True)),
                ('customerName', models.CharField(max_length=200)),
                ('contactNo', models.IntegerField()),
                ('email', models.CharField(blank=True, max_length=2000)),
                ('address', models.TextField(blank=True, null=True)),
                ('Pincode', models.IntegerField(null=True)),
                ('deviceType', models.CharField(max_length=200)),
                ('Serial_no', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('deviceModel', models.CharField(max_length=200)),
                ('problemCategory', models.CharField(max_length=100)),
                ('problem', models.CharField(blank=True, max_length=200, null=True)),
                ('deviceCondition', models.TextField(blank=True, null=True)),
                ('minimum_charge', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualProblem', models.CharField(max_length=50)),
                ('actualProblemDescription', models.TextField()),
                ('estimatedCost', models.IntegerField()),
                ('advance', models.IntegerField()),
                ('Enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expertlaptop.enquiry')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskTiltle', models.CharField(max_length=122)),
                ('TaskDescription', models.TextField(max_length=122)),
                ('Date', models.DateField(auto_now_add=True)),
                ('EmployeeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_name', to=settings.AUTH_USER_MODEL)),
                ('Enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry', to='expertlaptop.enquiry')),
                ('TaskCreatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Component_name', models.CharField(max_length=200)),
                ('Component_quantity', models.IntegerField()),
                ('Component_amount', models.FloatField()),
                ('accessories_quantity', models.IntegerField()),
                ('accessories_price', models.IntegerField()),
                ('Enquiry_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expertlaptop.enquiry')),
            ],
        ),
        migrations.CreateModel(
            name='Labour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(max_length=5000)),
                ('Hours', models.IntegerField()),
                ('Unit', models.IntegerField()),
                ('Labour_Charge', models.FloatField()),
                ('Enquiry_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expertlaptop.enquiry')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField()),
                ('CustomerName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expertlaptop.enquiry')),
            ],
        ),
    ]
