# Generated by Django 3.2.9 on 2021-11-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertlaptop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='total_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='labour',
            name='Description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='labour',
            name='Hours',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='labour',
            name='Labour_Charge',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='labour',
            name='Unit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Component_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Component_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='accessories_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='accessories_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
